# nixpacks.toml

[variables]
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_OMIT = ""
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[phases.install]
cmds = [
  "node -v",
  "npm -v",

  # Явно ставим devDeps (tsc нужен для build)
  "npm ci --include=dev --no-audit --no-fund"
]

[phases.build]
cmds = [
  # Проверка, что tsc реально есть
  "npx --no-install tsc -v",
  "npm run build"
]

[start]
cmd = "npm run start"
